name: miniconda3

channels:
  - conda-forge
  - nodefaults

dependencies:
  - m2-msys2-runtime
  - m2-which
  - m2-sed
  - m2-gzip
  - m2w64-gcc
  - m2w64-gsl
  - msmpi
  - pyaml
  - ply
  - numpy
  - tornado
  - scipy
  - pillow
  - pyqtgraph
  - pyqt
  - qtpy
  - qscintilla2
  - nexus
  - nexusformat
  - nexpy
  - hdf5
  - mcpl
  - mcpl-extra
  - ncrystal
  - mcpl
  - mcpl-core
  - mcpl-extra
  - xraylib
  - jupytext
  - jupyterlab
  - ipympl
  - jinja2
  - mslex
  - typish
  - jsons
  - nodejs
  - McStasScript
  - pip
